// SPDX-License-Identifier: GPL-2.0+
/*
 * Copyright (C) 2016~2024 Synaptics Incorporated. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 or
 * later as published by the Free Software Foundation.
 *
 * INFORMATION CONTAINED IN THIS DOCUMENT IS PROVIDED "AS-IS," AND
 * SYNAPTICS EXPRESSLY DISCLAIMS ALL EXPRESS AND IMPLIED WARRANTIES,
 * INCLUDING ANY IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE, AND ANY WARRANTIES OF NON-INFRINGEMENT OF ANY
 * INTELLECTUAL PROPERTY RIGHTS. IN NO EVENT SHALL SYNAPTICS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR
 * CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN CONNECTION WITH THE USE
 * OF THE INFORMATION CONTAINED IN THIS DOCUMENT, HOWEVER CAUSED AND
 * BASED ON ANY THEORY OF LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * NEGLIGENCE OR OTHER TORTIOUS ACTION, AND EVEN IF SYNAPTICS WAS
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. IF A TRIBUNAL OF
 * COMPETENT JURISDICTION DOES NOT PERMIT THE DISCLAIMER OF DIRECT
 * DAMAGES OR ANY OTHER DAMAGES, SYNAPTICS' TOTAL CUMULATIVE LIABILITY
 * TO ANY PARTY SHALL NOT EXCEED ONE HUNDRED U.S. DOLLARS.
 */

#define LCDC_REG_INTR               (RA_LCDC_cfgReg + 0x0000)
#define LCDC_REG_INTSR              (RA_LCDC_cfgReg + 0x0004)
#define LCDC_REG_INTER              (RA_LCDC_cfgReg + 0x0008)
#define LCDC_REG_LCDCCR             (RA_LCDC_cfgReg + 0x0010)
#define LCDC_REG_INTMR              (RA_LCDC_cfgReg + 0x0020)
#define LCDC_REG_DISPCR             (RA_LCDC_cfgReg + 0x0024)
#define LCDC_REG_OSDMCR             (RA_LCDC_cfgReg + 0x0028)
#define LCDC_REG_INDXSR             (RA_LCDC_cfgReg + 0x0044)
#define LCDC_REG_INDYSR             (RA_LCDC_cfgReg + 0x0048)
#define LCDC_REG_DISPXSPOSR         (RA_LCDC_cfgReg + 0x0050)
#define LCDC_REG_DISPXEPOSR         (RA_LCDC_cfgReg + 0x0054)
#define LCDC_REG_DISPYSPOS1R        (RA_LCDC_cfgReg + 0x0060)
#define LCDC_REG_DISPYEPOS1R        (RA_LCDC_cfgReg + 0x0064)
#define LCDC_REG_DISPYSPOS2R        (RA_LCDC_cfgReg + 0x0068)
#define LCDC_REG_DISPYEPOS2R        (RA_LCDC_cfgReg + 0x006c)
#define LCDC_REG_DISPIDXR           (RA_LCDC_cfgReg + 0x0090)
#define LCDC_REG_BACKCPR            (RA_LCDC_cfgReg + 0x0140)
#define LCDC_REG_RBCR               (RA_LCDC_cfgReg + 0x0150)
#define LCDC_REG_GBCR               (RA_LCDC_cfgReg + 0x0154)
#define LCDC_REG_BBCR               (RA_LCDC_cfgReg + 0x0158)
#define LCDC_REG_GC0R               (RA_LCDC_cfgReg + 0x0160)
#define LCDC_REG_GC1R               (RA_LCDC_cfgReg + 0x0164)
#define LCDC_REG_GC2R               (RA_LCDC_cfgReg + 0x0168)
#define LCDC_REG_GC3R               (RA_LCDC_cfgReg + 0x016c)
#define LCDC_REG_GC4R               (RA_LCDC_cfgReg + 0x0170)
#define LCDC_REG_GC5R               (RA_LCDC_cfgReg + 0x0174)
#define LCDC_REG_GC6R               (RA_LCDC_cfgReg + 0x0178)
#define LCDC_REG_GC7R               (RA_LCDC_cfgReg + 0x017c)
#define LCDC_REG_GC8R               (RA_LCDC_cfgReg + 0x0180)
#define LCDC_REG_GC9R               (RA_LCDC_cfgReg + 0x0184)
#define LCDC_REG_GC10R              (RA_LCDC_cfgReg + 0x0188)
#define LCDC_REG_GC10R              (RA_LCDC_cfgReg + 0x0188)
#define LCDC_REG_GC10R              (RA_LCDC_cfgReg + 0x0188)
#define LCDC_REG_GC11R              (RA_LCDC_cfgReg + 0x018c)
#define LCDC_REG_GC12R              (RA_LCDC_cfgReg + 0x0190)
#define LCDC_REG_GC13R              (RA_LCDC_cfgReg + 0x0194)
#define LCDC_REG_GC14R              (RA_LCDC_cfgReg + 0x0198)
#define LCDC_REG_GC15R              (RA_LCDC_cfgReg + 0x019c)
#define LCDC_REG_GC16R              (RA_LCDC_cfgReg + 0x01a0)
#define LCDC_REG_GCER               (RA_LCDC_cfgReg + 0x01a4)
#define LCDC_REG_YCLPCR             (RA_LCDC_cfgReg + 0x0200)
#define LCDC_REG_CCLPCR             (RA_LCDC_cfgReg + 0x0204)
#define LCDC_REG_CLPER              (RA_LCDC_cfgReg + 0x0208)
#define LCDC_REG_DISPIR             (RA_LCDC_cfgReg + 0x0240)
#define LCDC_REG_PANCSR             (RA_LCDC_cfgReg + 0x0250)
#define LCDC_REG_VSTR               (RA_LCDC_cfgReg + 0x0270)
#define LCDC_REG_VFTR               (RA_LCDC_cfgReg + 0x0274)
#define LCDC_REG_VATR               (RA_LCDC_cfgReg + 0x0278)
#define LCDC_REG_VETR               (RA_LCDC_cfgReg + 0x027C)
#define LCDC_REG_HSTR               (RA_LCDC_cfgReg + 0x0280)
#define LCDC_REG_HFTR               (RA_LCDC_cfgReg + 0x0284)
#define LCDC_REG_HADSTR             (RA_LCDC_cfgReg + 0x0288)
#define LCDC_REG_HAPWR              (RA_LCDC_cfgReg + 0x028c)
#define LCDC_REG_HETR               (RA_LCDC_cfgReg + 0x0290)
#define LCDC_REG_CTLTR0             (RA_LCDC_cfgReg + 0x02a8)
#define LCDC_REG_CMDFSR             (RA_LCDC_cfgReg + 0x02c0)
#define LCDC_REG_CMDAR              (RA_LCDC_cfgReg + 0x02c4)
#define LCDC_REG_TXDR               (RA_LCDC_cfgReg + 0x02c8)
#define LCDC_REG_RXDR               (RA_LCDC_cfgReg + 0x02cc)
#define LCDC_REG_GP0A_H_HI          (RA_LCDC_cfgReg + 0x0310)
#define LCDC_REG_GP0A_V_ST          (RA_LCDC_cfgReg + 0x0314)
#define LCDC_REG_GP0A_H_LO          (RA_LCDC_cfgReg + 0x0318)
#define LCDC_REG_GP0A_V_END         (RA_LCDC_cfgReg + 0x031c)
#define LCDC_REG_GP0ACNTR           (RA_LCDC_cfgReg + 0x0320)
#define LCDC_REG_GP0B_H_HI          (RA_LCDC_cfgReg + 0x0330)
#define LCDC_REG_GP0B_V_ST          (RA_LCDC_cfgReg + 0x0334)
#define LCDC_REG_GP0B_H_LO          (RA_LCDC_cfgReg + 0x0338)
#define LCDC_REG_GP0B_V_END         (RA_LCDC_cfgReg + 0x033c)
#define LCDC_REG_GP0BCNTR           (RA_LCDC_cfgReg + 0x0340)
#define LCDC_REG_GP1A_H_HI          (RA_LCDC_cfgReg + 0x0350)
#define LCDC_REG_GP1A_V_ST          (RA_LCDC_cfgReg + 0x0354)
#define LCDC_REG_GP1A_H_LO          (RA_LCDC_cfgReg + 0x0358)
#define LCDC_REG_GP1A_V_END         (RA_LCDC_cfgReg + 0x035c)
#define LCDC_REG_GP1ACNTR           (RA_LCDC_cfgReg + 0x0360)
#define LCDC_REG_GP1B_H_HI          (RA_LCDC_cfgReg + 0x0370)
#define LCDC_REG_GP1B_V_ST          (RA_LCDC_cfgReg + 0x0374)
#define LCDC_REG_GP1B_H_LO          (RA_LCDC_cfgReg + 0x0378)
#define LCDC_REG_GP1B_V_END         (RA_LCDC_cfgReg + 0x037c)
#define LCDC_REG_GP1BCNTR           (RA_LCDC_cfgReg + 0x0380)
#define LCDC_REG_GP2_H_HI           (RA_LCDC_cfgReg + 0x0390)
#define LCDC_REG_GP2_V_ST           (RA_LCDC_cfgReg + 0x0394)
#define LCDC_REG_GP2_H_LO           (RA_LCDC_cfgReg + 0x0398)
#define LCDC_REG_GP2_V_END          (RA_LCDC_cfgReg + 0x039c)
#define LCDC_REG_GP2_H_EX           (RA_LCDC_cfgReg + 0x03a0)
#define LCDC_REG_GP2_V_EX           (RA_LCDC_cfgReg + 0x03a4)
#define LCDC_REG_GP2CNTR            (RA_LCDC_cfgReg + 0x03a8)
#define LCDC_REG_GP3_H_HI           (RA_LCDC_cfgReg + 0x03b0)
#define LCDC_REG_GP3_V_ST           (RA_LCDC_cfgReg + 0x03b4)
#define LCDC_REG_GP3_H_LO           (RA_LCDC_cfgReg + 0x03b8)
#define LCDC_REG_GP3_V_END          (RA_LCDC_cfgReg + 0x03bc)
#define LCDC_REG_GP3_H_EX           (RA_LCDC_cfgReg + 0x03c0)
#define LCDC_REG_GP3_V_EX           (RA_LCDC_cfgReg + 0x03c4)
#define LCDC_REG_GP3CNTR            (RA_LCDC_cfgReg + 0x03c8)
#define LCDC_REG_GP4_H_HI           (RA_LCDC_cfgReg + 0x03d0)
#define LCDC_REG_GP4_V_ST           (RA_LCDC_cfgReg + 0x03d4)
#define LCDC_REG_GP4_H_LO           (RA_LCDC_cfgReg + 0x03d8)
#define LCDC_REG_GP4_V_END          (RA_LCDC_cfgReg + 0x03dc)
#define LCDC_REG_GP4CNTR            (RA_LCDC_cfgReg + 0x03e0)
#define LCDC_REG_GP5_H_HI           (RA_LCDC_cfgReg + 0x03f0)
#define LCDC_REG_GP5_V_ST           (RA_LCDC_cfgReg + 0x03f4)
#define LCDC_REG_GP5_H_LO           (RA_LCDC_cfgReg + 0x03f8)
#define LCDC_REG_GP5_V_END          (RA_LCDC_cfgReg + 0x03fc)
#define LCDC_REG_GP5CNTR            (RA_LCDC_cfgReg + 0x0400)
#define LCDC_REG_GP6_H_HI           (RA_LCDC_cfgReg + 0x0410)
#define LCDC_REG_GP6_V_ST           (RA_LCDC_cfgReg + 0x0414)
#define LCDC_REG_GP6_H_LO           (RA_LCDC_cfgReg + 0x0418)
#define LCDC_REG_GP6_V_END          (RA_LCDC_cfgReg + 0x041c)
#define LCDC_REG_GP6CNTR            (RA_LCDC_cfgReg + 0x0420)
#define LCDC_REG_GP7_H_HI           (RA_LCDC_cfgReg + 0x0430)
#define LCDC_REG_GP7_V_ST           (RA_LCDC_cfgReg + 0x0434)
#define LCDC_REG_GP7_H_LO           (RA_LCDC_cfgReg + 0x0438)
#define LCDC_REG_GP7_V_END          (RA_LCDC_cfgReg + 0x043c)
#define LCDC_REG_GP7CNTR            (RA_LCDC_cfgReg + 0x0440)
#define LCDC_REG_GP8A_H_HI          (RA_LCDC_cfgReg + 0x0450)
#define LCDC_REG_GP8A_V_ST          (RA_LCDC_cfgReg + 0x0454)
#define LCDC_REG_GP8A_H_LO          (RA_LCDC_cfgReg + 0x0458)
#define LCDC_REG_GP8A_V_END         (RA_LCDC_cfgReg + 0x045c)
#define LCDC_REG_GP8ACNTR           (RA_LCDC_cfgReg + 0x0460)
#define LCDC_REG_GP8B_H_HI          (RA_LCDC_cfgReg + 0x0470)
#define LCDC_REG_GP8B_V_ST          (RA_LCDC_cfgReg + 0x0474)
#define LCDC_REG_GP8B_H_LO          (RA_LCDC_cfgReg + 0x0478)
#define LCDC_REG_GP8B_V_END         (RA_LCDC_cfgReg + 0x047c)
#define LCDC_REG_GP8BCNTR           (RA_LCDC_cfgReg + 0x0480)
#define LCDC_REG_GP_HMAXR           (RA_LCDC_cfgReg + 0x0490)
#define LCDC_REG_GP_VMAXR           (RA_LCDC_cfgReg + 0x0494)
#define LCDC_REG_GPSELR             (RA_LCDC_cfgReg + 0x04a0)
#define LCDC_REG_PARUP              (RA_LCDC_cfgReg + 0x04d0)
#define LCDC_REG_CDISPUPR           (RA_LCDC_cfgReg + 0x04d4)
#define LCDC_REG_ISTAR0             (RA_LCDC_cfgReg + 0x04f0)
#define LCDC_REG_ISTAR1             (RA_LCDC_cfgReg + 0x04f4)
#define LCDC_REG_ISTAR2             (RA_LCDC_cfgReg + 0x04f8)
#define LCDC_REG_ISTAR3             (RA_LCDC_cfgReg + 0x04fc)
#define LCDC_REG_ISTAR4             (RA_LCDC_cfgReg + 0x0500)
#define LCDC_REG_CMDFIFOR0          (RA_LCDC_cfgReg + 0x0528)
#define LCDC_REG_CMDFIFOR1          (RA_LCDC_cfgReg + 0x052c)
#define LCDC_REG_CMDFIFOR2          (RA_LCDC_cfgReg + 0x0530)
#define LCDC_REG_CMDFIFOR3          (RA_LCDC_cfgReg + 0x0534)
#define LCDC_REG_CMDFIFOR4          (RA_LCDC_cfgReg + 0x0538)
#define LCDC_REG_CMDFIFOR5          (RA_LCDC_cfgReg + 0x053c)
#define LCDC_REG_CMDFIFOR6          (RA_LCDC_cfgReg + 0x0540)
#define LCDC_REG_CMDFIFOR7          (RA_LCDC_cfgReg + 0x0544)
#define LCDC_REG_CMDFIFOR8          (RA_LCDC_cfgReg + 0x0548)
#define LCDC_REG_CMDFIFOR9          (RA_LCDC_cfgReg + 0x054c)
#define LCDC_REG_CMDFIFOR10         (RA_LCDC_cfgReg + 0x0550)
#define LCDC_REG_CMDFIFOR11         (RA_LCDC_cfgReg + 0x0554)
#define LCDC_REG_RSCMDR             (RA_LCDC_cfgReg + 0x0558)
#define LCDC_REG_RWCMDR             (RA_LCDC_cfgReg + 0x055c)
#define LCDC_REG_LCMDR              (RA_LCDC_cfgReg + 0x0560)
